services:
  serveur_mongo:
    image: mongo:7
    container_name: la_base_mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}

  script_python:
    build: .
    container_name: mon_script_migration
    depends_on:
      - serveur_mongo
    volumes:
      - ./:/app
    environment:
      - MONGO_HOST=la_base_mongodb
      - MONGO_USER=admin_medical
      - MONGO_MDP=Louvre
volumes:
  mongo_data: